name: MagicItems
version: '${project.version}'
main: net.pullolo.magicitems.MagicItems
api-version: '1.21'
commands:
  roll:
    usage: /<command> <?scroll>
    description: Allows you to re-roll special items!
    permission: mi-roll