name: MagicItems
version: '${project.version}'
main: net.pullolo.magicitems.MagicItems
api-version: '1.20'
commands:
  roll:
    usage: /<command>
    description: Allows you to re-roll special items!
    permission: mi-roll
